// Auth actions
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FORGET_PASSWORD_REQUEST_SENT = 'FORGET_PASSWORD_REQUEST_SENT';
export const VERIFY_CODE_CORRECT = 'VERIFY_CODE_CORRECT';
export const RESET_PASSWORD_DONE = 'RESET_PASSWORD_DONE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

// Markets actions
export const MARKETS_LIST_FETCHED = 'MARKETS_LIST_FETCHED';
export const MARKET_FETCHED = 'MARKET_FETCHED';
export const MARKET_CATEGORIES_FETCHED = 'MARKET_CATEGORIES_FETCHED';
export const MARKET_ITEMS_FETCHED = 'MARKET_ITEMS_FETCHED';
export const MARKET_ITEMS_FILTER_FETCHED = 'MARKET_ITEMS_FILTER_FETCHED';
export const NAVIGATE_TO_MARKET = 'NAVIGATE_TO_MARKET';
export const TOGGLE_IS_FAVORITE = 'TOGGLE_IS_FAVORITE';
// Orders actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECKOUT = 'CHECKOUT';
export const ORDER_CREATED = 'ORDER_CREATED';
export const ADDRESS_CREATED = 'ADDRESS_CREATED';
export const ORDERS_LIST_FETCHED = 'ORDERS_LIST_FETCHED';
export const ORDER_FETCHED_BY_ID = 'ORDER_FETCHED_BY_ID';
export const SET_ORDER_EDIT_MODE = 'SET_ORDER_EDIT_MODE';
export const ORDER_UPDATED = 'ORDER_UPDATED';
export const ORDER_CANCELED = 'ORDER_CANCELED';
export const MARKET_RATED = 'MARKET_RATED';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const RE_ORDER_MODE = 'RE_ORDER_MODE';
export const ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED';
export const EMPTY_CART = 'EMPTY_CART';
// offers
export const OFFERS_LIST_FETCHED = 'OFFERS_LIST_FETCHED';
export const OFFERS_LIST_IS_LOADING = 'OFFERS_LIST_IS_LOADING';
//chats
export const AVAILABLE_CHATS_FETCHED = 'AVAILABLE_CHATS_FETCHED';
export const MESSAGES_FETCHED = 'MESSAGES_FETCHED';
export const UPDATE_CHAT = 'UPDATE_CHAT';
// menu
export const ALL_CATEGORIES_FETCHED = 'ALL_CATEGORIES_FETCHED';
export const CLEAR_ALL_MENU_ITEMS = 'CLEAR_ALL_MENU_ITEMS';
export const ITEMS_BY_CATEGORY_FETCHED = 'ITEMS_BY_CATEGORY_FETCHED';
export const ADD_ITEM_TO_MENU = 'ADD_ITEM_TO_MENU';
export const REMOVE_FROM_MENU = 'REMOVE_FROM_MENU';

//snackbar
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
